src/myapps/crypto/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.stat_view, name='stat_view'),
    url(r'^details/(?P<pair_id>[\w-]+)/$', views.details, name='details'),
    url(r'^edit/(?P<pair_id>[\w-]+)/$', views.edit, name='edit'),
]

src/myapps/english/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.list_words, name='list_words'),
    url(r'^add/$', views.add_words, name='add_words'),
    url(r'^edit/(?P<word_id>[\w-]+)/$', views.edit_words, name='edit_words'),
    url(r'^delete/(?P<word_id>[\w-]+)/$', views.delete_words, name='delete_words'),
]

src/myapps/quicknote/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.list_notes, name='list_notes'),
    url(r'^add/$', views.add_note, name='add_note'),
    url(r'^edit/(?P<note_id>[\w-]+)/$', views.edit_note, name='edit_note'),
    url(r'^delete/(?P<note_id>[\w-]+)/$', views.delete_note, name='delete_note'),
]

src/myapps/tryinsta/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.users, name='users'),
    url(r'^media/(?P<tc_user_id>[\w-]+)/$', views.user_media, name='user_media'),
]

src/settings/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sportlife/', include('myapps.sportlife.urls', namespace='sportlife')),
    url(r'^english/', include('myapps.english.urls', namespace='english')),
    url(r'^quicknote/', include('myapps.quicknote.urls', namespace='quicknote')),
    url(r'^$', auth_view.login, {'template_name': 'base.html'}, name='login'),
    # url(r'^logout/$', auth_view.logout, {'next_page': '/english/'}, name='logout'),
    url(r'^logout/$', auth_view.logout, name='logout'),
    url(r'^crypto/', include('myapps.crypto.urls', namespace='crypto')),
    url(r'^tryinsta/', include('myapps.tryinsta.urls', namespace='tryinsta')),
]

src/templates/base.html
<!doctype html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Personal notebook" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    {% load staticfiles %}
<!--bootstrap-->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
<!--coustom css-->
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
<!--script-->
<script src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
<!-- js -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- /js -->
<!--fonts-->
<link href='//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400italic,400,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!--/fonts-->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
<!--script-->
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
</script>
<!--/script-->
</head>
	<body>
<!--header-->
		<div class="header" id="home">
			<nav class="navbar navbar-default">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"> </span>
						<span class="icon-bar"> </span>
						<span class="icon-bar"> </span>
					</button>
					<h1><a class="navbar-brand" href="{% url 'english:list_words' %}">Notebook<br /><span>Personal</span></a></h1>
					</div>
					<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="nav navbar-nav navbar-right margin-top cl-effect-2">
								<li><a href="{% url 'english:list_words' %}"><span data-hover="Gallery">English</span></a></li>
								<li><a href="#"><span data-hover="Gallery">Sport Life</span></a></li>
								<li><a href="{% url 'quicknote:list_notes' %}"><span data-hover="Gallery">Quick Note</span></a></li>
								<li><a href="{% url 'crypto:stat_view' %}"><span data-hover="Gallery">Crypto</span></a></li>
								<li><a href="{% url 'tryinsta:users' %}"><span data-hover="Gallery">TryInsta</span></a></li>
							</ul>
							<div class="clearfix"> </div>
						</div><!-- /.navbar-collapse -->
				<!-- /.container-fluid -->

                    {% if user.is_authenticated %}

                    <div class="login-pop">
							<a href="{% url 'logout' %}" id="logoutButton">{{ user.username }} (logout)</a>
                    </div>

                    {% else %}

                    <div class="login-pop">
						<div id="loginpop"><a href="#" id="loginButton"><span>Login</span></a>
								<div id="loginBox">
                                    <form id="loginForm" method="post">
                                        {% csrf_token %}
											<fieldset id="body">
												<fieldset>
                                                    <label for="id_username">Username</label>
                                                    <input type="text" name="username"
                                                           autofocus required maxlength="254" id="id_username" />
												</fieldset>
												<fieldset>
                                                    <label for="id_password">Password</label>
                                                    <input type="password" name="password" required id="id_password" />
												 </fieldset>
												<input type="submit" id="login" value="Sign in">
											</fieldset>
                                    </form>
							</div>
					    </div>
					    </div><script src="{% static 'js/menu_jquery.js' %}"></script>
                    {% endif %}
                </div>
			</nav>
<!--/script-->
		   <div class="clearfix"> </div>
</div>
<!-- Top Navigation -->
<div class="banner banner5">
	<div class="container">
	<h2>{% block pagename %}{% endblock %}</h2>
	</div>
</div>
<!--header-->

<!-- body here -->
{% block content %}
{% endblock %}
<!-- /body here -->

<!--footer-->
<div class="footer">
		<!-- container -->
		<div class="container">
			<div class="col-md-6 footer-left">
				<ul>
					<li><a href="{% url 'english:list_words' %}">English</a></li>
					<li><a href="#">Sport Life</a></li>
                    <li><a href="{% url 'quicknote:list_notes' %}">Quick Note</a></li>
					<li><a href="{% url 'crypto:stat_view' %}">Crypto</a></li>
                    <li><a href="{% url 'tryinsta:users' %}">TryInsta</a></li>
				</ul>
			</div>
			<div class="col-md-3 footer-middle">
				<h3>Address</h3>
				<div class="address">
					<p>Earth
						<span>Europe, Kyiv</span>
					</p>
				</div>
				<div class="phone">
					<p>+38(099)123-4567-89</p>
				</div>
			</div>
			<div class="col-md-3 footer-right">
				<h3>Notebook info</h3>
				<p>Nothing special, just some personal stuff</p>
			</div>
			<div class="clearfix"> </div>
		</div>
		<!-- //container -->
	</div>
<!--/footer-->
<!--copy-rights-->
<div class="copyright">
		<!-- container -->
		<div class="container">
			<div class="copyright-left">
			<p> © 2018 Education Tutorial. All rights reserved | Design by
                <a href="http://w3layouts.com/">W3layouts</a></p>
			</div>
			<div class="copyright-right">
				<ul>
					<li><a href="#" class="twitter"> </a></li>
					<li><a href="#" class="twitter facebook"> </a></li>
					<li><a href="#" class="twitter chrome"> </a></li>
					<li><a href="#" class="twitter linkedin"> </a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>

		</div>
		<!-- //container -->
				<!---->
<script type="text/javascript">
		$(document).ready(function() {
				/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
				*/
		$().UItoTop({ easingType: 'easeOutQuart' });
});
</script>
<a href="#to-top" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<!---->
	</div>
<!--/copy-rights-->
	</body>
</html>